version: "3"

volumes:
  postgres_data:
    driver: local
  influxdb_data:
    driver: local

services:
  postgresdb:
    image: postgres:14-alpine
    ports:
      - "5597:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
  influxdb:
    image: influxdb:2.2-alpine
    volumes:
      - influxdb_data:/var/lib/influxdb2/data
    ports:
      - "8085:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=nexus
      - DOCKER_INFLUXDB_INIT_PASSWORD=nexus_dev
      - DOCKER_INFLUXDB_INIT_ORG=nexus_metrics
      - DOCKER_INFLUXDB_INIT_BUCKET=nexus
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=devtoken